### PR TITLE
Ecto2 support (alpha)

### PR DESCRIPTION
**Pull request by mjaric**
Hi,

This pull request should be good to go with alpha for testing purpose. Could you please give it a try? 

I will also check how query works on existing database, there is small app I need to write. I will send you info as soon as I finish this app.

### CODE REVIEW

**Comment by brentweber** [comment]
Hi my name is Brent Weber and I work with LiveHelpNow. I am beginning to test this branch, if I have any questions I will reach out. Sorry for the delay.

**Comment by brentweber** [comment]
basic query of model returning nil: 
Performing repo.get passing in the model and an id and the result returned is always nil. I tried repo.get on other models and got the same result, nil. Btw this nil result is from an existing database, not one generated through elixir. Please let me know if you have any questions for me.

**Comment by brentweber** [comment]
I updated some stuff this morning and double checked some things on my end to make sure I am not doing something wrong. I still have the model returning nil issue but now I am also getting a more meaningful error. Thought this may help, error is in snippet below. 
`[error] GenServer #PID<0.1898.0> terminating
** (DBConnection.ConnectionError) client #PID<0.1919.0> stopped: ** (FunctionClauseError) no function clause matching in Tds.Tokens.decode_token/2
    (tds) lib/tds/tokens.ex:41: Tds.Tokens.decode_token(<<110, 0, 97, 0, 103, 0, 101, 0, 109, 0, 101, 0, 110, 0, 116, 0, 60, 0, 47, 0, 97, 0, 62, 0, 32, 0, 97, 0, 110, 0, 100, 0, 32, 0, 97, 0, 38, 0, 110, 0, 98, 0, 115, 0, 112, 0, 59, 0, 60, 0, ...>>, [])
    (tds) lib/tds/tokens.ex:37: Tds.Tokens.decode_tokens/2
    (tds) lib/tds/messages.ex:93: Tds.Messages.parse/4
    (tds) lib/tds/protocol.ex:255: Tds.Protocol.new_data/2
    (tds) lib/tds/protocol.ex:379: Tds.Protocol.send_param_query/3
    (db_connection) lib/db_connection.ex:958: DBConnection.handle/4
    (db_connection) lib/db_connection.ex:1078: DBConnection.describe_run/5
    (db_connection) lib/db_connection.ex:1142: anonymous fn/4 in DBConnection.run_meter/5
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (tds_ecto) lib/tds_ecto/connection.ex:59: Tds.Ecto.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:441: Ecto.Adapters.SQL.execute_or_reset/7
    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:68: Ecto.Repo.Queryable.one/4
    (knowledge_base) web/plugs/client.ex:16: KnowledgeBase.Plugs.Client.get_client/1
    (knowledge_base) lib/knowledge_base/endpoint.ex:1: KnowledgeBase.Endpoint.phoenix_pipeline/1
    (knowledge_base) lib/plug/debugger.ex:123: KnowledgeBase.Endpoint."call (overridable 3)"/2
    (knowledge_base) lib/knowledge_base/endpoint.ex:1: KnowledgeBase.Endpoint.call/2

    (db_connection) lib/db_connection/connection.ex:243: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:489: Connection.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:stop, #Reference<0.0.1.3629>, %DBConnection.ConnectionError{message: "client #PID<0.1919.0> stopped: ** (FunctionClauseError) no function clause matching in Tds.Tokens.decode_token/2\n    (tds) lib/tds/tokens.ex:41: Tds.Tokens.decode_token(<<110, 0, 97, 0, 103, 0, 101, 0, 109, 0, 101, 0, 110, 0, 116, 0, 60, 0, 47, 0, 97, 0, 62, 0, 32, 0, 97, 0, 110, 0, 100, 0, 32, 0, 97, 0, 38, 0, 110, 0, 98, 0, 115, 0, 112, 0, 59, 0, 60, 0, ...>>, [])\n    (tds) lib/tds/tokens.ex:37: Tds.Tokens.decode_tokens/2\n    (tds) lib/tds/messages.ex:93: Tds.Messages.parse/4\n    (tds) lib/tds/protocol.ex:255: Tds.Protocol.new_data/2\n    (tds) lib/tds/protocol.ex:379: Tds.Protocol.send_param_query/3\n    (db_connection) lib/db_connection.ex:958: DBConnection.handle/4\n    (db_connection) lib/db_connection.ex:1078: DBConnection.describe_run/5\n    (db_connection) lib/db_connection.ex:1142: anonymous fn/4 in DBConnection.run_meter/5\n    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3\n    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4\n    (tds_ecto) lib/tds_ecto/connection.ex:59: Tds.Ecto.Connection.execute/4\n    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6\n    (ecto) lib/ecto/adapters/sql.ex:441: Ecto.Adapters.SQL.execute_or_reset/7\n    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5\n    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4\n    (ecto) lib/ecto/repo/queryable.ex:68: Ecto.Repo.Queryable.one/4\n    (knowledge_base) web/plugs/client.ex:16: KnowledgeBase.Plugs.Client.get_client/1\n    (knowledge_base) lib/knowledge_base/endpoint.ex:1: KnowledgeBase.Endpoint.phoenix_pipeline/1\n    (knowledge_base) lib/plug/debugger.ex:123: KnowledgeBase.Endpoint.\"call (overridable 3)\"/2\n    (knowledge_base) lib/knowledge_base/endpoint.ex:1: KnowledgeBase.Endpoint.call/2\n"}, %Tds.Protocol{env: %{trans: <<0>>}, itcp: nil, opts: [password: :REDACTED, idle_timeout: 5000, name: LhnDb.Repo.Knowledge.Pool, otp_app: :lhn_db, repo: LhnDb.Repo.Knowledge, adapter: Tds.Ecto, hostname: "db.sql.livehelpnow.dev", username: "lhnelixir", database: "livehelpnow_knowledge", size: 1, max_overflow: 0, pool_timeout: 5000, timeout: 15000, adapter: Tds.Ecto, hostname: "db.sql.livehelpnow.dev", username: "lhnelixir", database: "livehelpnow_knowledge", size: 1, max_overflow: 0, pool: DBConnection.Poolboy], pak_data: <<110, 0, 97, 0, 103, 0, 101, 0, 109, 0, 101, 0, 110, 0, 116, 0, 60, 0, 47, 0, 97, 0, 62, 0, 32, 0, 97, 0, 110, 0, 100, 0, 32, 0, 97, 0, 38, 0, 110, 0, 98, 0, 115, ...>>, pak_header: <<46, 0, 46, 0, 66, 0, 85, 0>>, query: %Tds.Query{handle: 2, statement: nil}, result: %Tds.Result{columns: [], command: nil, num_rows: 0, rows: []}, sock: {:gen_tcp, #Port<0.138661>}, state: :ready, tail: <<84, 0, 46, 0, 46, 0, 46, 0, 72, 0, 111, 0, 119, 0, 32, 0, 109, 0, 97, 0, 110, 0, 121, 0, 32, 0, 111, 0, 102, 0, 32, 0, 116, 0, 104, 0, 101, ...>>, transaction: nil, usock: nil}}
State: {Tds.Protocol, %Tds.Protocol{env: %{trans: <<0>>}, itcp: nil, opts: [password: :REDACTED, idle_timeout: 5000, name: LhnDb.Repo.Knowledge.Pool, otp_app: :lhn_db, repo: LhnDb.Repo.Knowledge, adapter: Tds.Ecto, hostname: "db.sql.livehelpnow.dev", username: "lhnelixir", database: "livehelpnow_knowledge", size: 1, max_overflow: 0, pool_timeout: 5000, timeout: 15000, adapter: Tds.Ecto, hostname: "db.sql.livehelpnow.dev", username: "lhnelixir", database: "livehelpnow_knowledge", size: 1, max_overflow: 0, pool: DBConnection.Poolboy], pak_data: <<110, 0, 97, 0, 103, 0, 101, 0, 109, 0, 101, 0, 110, 0, 116, 0, 60, 0, 47, 0, 97, 0, 62, 0, 32, 0, 97, 0, 110, 0, 100, 0, 32, 0, 97, 0, 38, 0, 110, 0, 98, 0, 115, 0, 112, ...>>, pak_header: <<46, 0, 46, 0, 66, 0, 85, 0>>, query: %Tds.Query{handle: 2, statement: nil}, result: %Tds.Result{columns: [], command: nil, num_rows: 0, rows: []}, sock: {:gen_tcp, #Port<0.138661>}, state: :ready, tail: <<84, 0, 46, 0, 46, 0, 46, 0, 72, 0, 111, 0, 119, 0, 32, 0, 109, 0, 97, 0, 110, 0, 121, 0, 32, 0, 111, 0, 102, 0, 32, 0, 116, 0, 104, 0, 101, 0, 109, ...>>, transaction: nil, usock: nil}}
[error] #PID<0.1919.0> running KnowledgeBase.Endpoint terminated
Server: localhost:4009 (http)
Request: GET /1
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Tds.Tokens.decode_token/2
        (tds) lib/tds/tokens.ex:41: Tds.Tokens.decode_token(<<110, 0, 97, 0, 103, 0, 101, 0, 109, 0, 101, 0, 110, 0, 116, 0, 60, 0, 47, 0, 97, 0, 62, 0, 32, 0, 97, 0, 110, 0, 100, 0, 32, 0, 97, 0, 38, 0, 110, 0, 98, 0, 115, 0, 112, 0, 59, 0, 60, 0, ...>>, [])
        (tds) lib/tds/tokens.ex:37: Tds.Tokens.decode_tokens/2
        (tds) lib/tds/messages.ex:93: Tds.Messages.parse/4
        (tds) lib/tds/protocol.ex:255: Tds.Protocol.new_data/2
        (tds) lib/tds/protocol.ex:379: Tds.Protocol.send_param_query/3
        (db_connection) lib/db_connection.ex:958: DBConnection.handle/4
        (db_connection) lib/db_connection.ex:1078: DBConnection.describe_run/5
        (db_connection) lib/db_connection.ex:1142: anonymous fn/4 in DBConnection.run_meter/5
        (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
        (tds_ecto) lib/tds_ecto/connection.ex:59: Tds.Ecto.Connection.execute/4
        (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
        (ecto) lib/ecto/adapters/sql.ex:441: Ecto.Adapters.SQL.execute_or_reset/7
        (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:68: Ecto.Repo.Queryable.one/4
        (knowledge_base) web/plugs/client.ex:16: KnowledgeBase.Plugs.Client.get_client/1
        (knowledge_base) lib/knowledge_base/endpoint.ex:1: KnowledgeBase.Endpoint.phoenix_pipeline/1
        (knowledge_base) lib/plug/debugger.ex:123: KnowledgeBase.Endpoint."call (overridable 3)"/2
        (knowledge_base) lib/knowledge_base/endpoint.ex:1: KnowledgeBase.Endpoint.call/2`

**Comment by andrei-mihaila** [comment]
It looks like an error in the tds repo to me. Very similar issues have been reported, please see comments https://github.com/livehelpnow/tds_ecto/issues/34#issuecomment-285969096 and https://github.com/livehelpnow/tds_ecto/issues/34#issuecomment-287636979.

**Comment by mjaric** [comment]
I can confirm thah tds driver is not working. And it is some odd behaviour. If package resujlt set contins more than 4096 bytes it may not pass parsing forsome reason. I managd to get result if i repeat same query couple of times. I didn't check what tds contains since size varry. My case was that in most cases i get nil if tds result contans exact 4096 bytes and wheni repeat same query few more times it may renturn result if there is 4196 bytes. It is not OS related since I checked it on OSX and Windows.

If you try other query where result has less than 4096 bytes it should return result in most cases. I think there is something in protocol which has to be covered in new_data function, or some other function beneath it which parse response. I havent had time yet to debug properly since for start I would need to decode tds by hand in order to figure out what is the cause.

**Pull request merged**
